### ISSUE TITLE
Inventory service access

### ISSUE THREAD

**Issue by jacquestardie** [mapbox/usgs#19]
Was looking to poke around with this, but am receiving the following:

```
  File "/usr/local/bin/usgs", line 9, in <module>
    load_entry_point('usgs==0.1.1.dev0', 'console_scripts', 'usgs')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/usgs/scripts/cli.py", line 65, in login
    api_key = api.login(username, password)
  File "/usr/local/lib/python2.7/site-packages/usgs/api.py", line 149, in login
    raise Exception(r.text)
Exception: <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>AUTH_ERROR</faultcode><faultstring>Authentication Failed: User does not have Inventory Service access.</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

The credentials I'm using are the same that I use for Earth Explorer, which work fine. Do I need to do anything fancy to get Inventory Service access?

Thanks!

**Comment by kapadia** [comment]
@jacquestardie some requests to the Inventory Service require privileged access (e.g. obtaining a download url). This is something you would have to arrange with USGS. Many other requests (e.g. search, metadata) work without authentication. You should be able to submit these requests without logging in.

**Comment by jacquestardie** [comment]
Sounds good, thanks!

**Comment by zotix** [comment]
How I get Inventory service access?

**Comment by jqtrde** [comment]
@zotix I actually never figured that out myself...

**Comment by kapadia** [comment]
@zotix  - you will be able to make anonymous requests for all the metadata you want without having inventory service access. Also, the USGS was doing maintenance on their servers last night. It appears they are back online now.

**Comment by zotix** [comment]
I want to download GeoTIFF Data Product and usgs api told me "usgs.USGSApiKeyRequiredError".
Do you have a example for download product?

**Comment by kapadia** [comment]
@zotix to be allowed downloads, you will need to request what the USGS calls "machine to machine" privileges for your EarthExplorer account. The best I can suggest is to email `lta@usgs.gov` to request escalated privileges. Privileges are granted on a case by case basis.

If you happen to be interested in Landsat 8 imagery, we (Planet Labs, Mapbox, AWS) have been making imagery available for easier access. Info at: https://aws.amazon.com/blogs/aws/start-using-landsat-on-aws/
